import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";

export const rage = localFont({
	src: [
		{
			path: "../public/fonts/rage_italic.woff2",
			weight: "400",
			style: "italic",
		},
	],
	variable: "--font-rage",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export const poppins = Poppins({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700", "900"],
	variable: "--font-poppins",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${poppins.variable} ${rage.variable} antialiased ${poppins.className}`}
			>
				{children}
			</body>
		</html>
	);
}
